### ISSUE TITLE
Variabele namen in hoofdletters zijn constants

### ISSUE THREAD

**Issue by BerendWeij** [florisdh/TowerDefense#1]
``` c
WINDOW_WIDTH = stage.stageWidth;
            WINDOW_HEIGHT = stage.stageHeight; 
```

Bestand: https://github.com/florisdh/TowerDefense/blob/master/src/Main.as

Schrijf niet de variabele namen met alleen hoofdletters als het geen constants zijn.
De code convention is dat je variabele namen alleen in hoofdletters schrijft als het constants zijn. Hierdoor weet iedereen aan de hand van de naam wat voor een type variabele het is.

**Comment by florisdh** [comment]
Ja ik begrijp de issue, had het eerst als constant op 1280, 720 omdat ik problemen had met positioneren relatief tot het scherm bij objecten die nog niet op de stage zitten. Had dit nog snel verandert naar de stage size voor als je het op andere resulution speelt, maar was vergeten de naam te veranderen.
