### ISSUE TITLE
Koppeling presentatie/view met code

### ISSUE THREAD

**Issue by BerendWeij** [florisdh/TowerDefense#11]
``` c
// Anim frames
            _anim_idle_begin = 0;
            _anim_idle_end = 50;
            _anim_walk_begin = 55;
            _anim_walk_end = 92;
            _anim_attack_begin = 100;
            _anim_attack_end = 175;
            _anim_death_begin = 185;
            _anim_death_end = 300;

            _attackRange = 100; 
```

Bestand: https://github.com/florisdh/TowerDefense/blob/master/src/GameObjects/Units/Enemies/Enemy_BeastRider.as

Je maakt een harde koppeling met de animatie. Dit probeer je uiteraard te vermijden voor je code. Had de artist niet met 'labels' kunnen werken? Dan hadden zij aan kunnen geven waar bijvoorbeeld een 'walk' begint. Dan had jij alleen maar hoeven weten dat er een walk was (en niet waar hij begon qua frame nummer).

**Comment by florisdh** [comment]
Ik begrijp dat dit beter is, heb het ook in al mijn andere projecten gedaan met tags. Voor dit project hadden de artist nog 'veel' te doen dus ik had het maar op deze manier gedaan
