### ISSUE TITLE
DRY - Do not repeat yourself

### ISSUE THREAD

**Issue by BerendWeij** [florisdh/TowerDefense#7]
``` c
dispatchEvent(new Event(DIED)); 
```

Bestand: https://github.com/florisdh/TowerDefense/blob/master/src/Humanoid.as

Probeer je functies zo te schrijven zodat je geen overlap hebt in regels code. Dit noem je DRY coderen. Do Not Repeat Yourself. Als je wel jezelf herhaalt qua code dan wordt je code niet alleen langer, maar je moet ook je code op meer plekken wijzigen als je toch iets moet veranderen aan de logica.

Ik zie dispatchEvent meerdere keren terugkomen. Probeer je code altijd te refactoren als je herhaling ziet (hoe klein deze herhaling ook is). Bijvoorbeeld naar een private dispatch() event. Dan heb je niet op 2 plekken new Event staan.

**Comment by florisdh** [comment]
Dus je bedoeld dat ik 2 functies maak onDied() en onChanged() die de dispatch uivoeren? dit zouden dan 2 functions zijn met 1 line of code, zie niet helemaal het idee ervan.
